### ISSUE TITLE
Quest board after first quest 

### ISSUE THREAD

**Issue by OrganicJuiceMan** [Chi-Time/DAC515-RPGMaker-Game#16]
After compleating the Ratsputin quest the names of the next dungeons are cannot be seen but the stats of the dungeon can be seen. the nameless dungeons can still be selected and will still teleport you to them

**Comment by Chi-Time** [comment]
Error is fixed. I've also disabled dungeon selection post-tutorial as it's not properly implemented yet and needs to be fleshes out properly next sprint.
